<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SpectraShade.Compiler.CLI</RootNamespace>
    <AssemblyName>ssc</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <SignAssembly>false</SignAssembly>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpectraShade.Compiler\SpectraShade.Compiler.csproj" />
    <ProjectReference Include="..\SpectraEngine.Core\SpectraEngine.Core.csproj" />
  </ItemGroup>

</Project>
