using SpectraEngine.Core.Graphics;
using System;
using System.Numerics;

namespace SpectraEngine.Editing.Gizmos;

/// <summary>
/// Draws the rotate gizmo into a <see cref="DebugDraw"/>: three axis rings in
/// the gizmo frame's planes plus a larger view-aligned ring, with the hovered or
/// active ring highlighted.
/// </summary>
/// <remarks>
/// Every circle here is generated by <see cref="GizmoColors.DrawCircle"/> in the
/// same basis and with the same segment count
/// (<see cref="GizmoHitTesting.RingSegments"/>) that
/// <see cref="RotateGizmoHitTester"/> walks, so the polygon the user aims at is
/// bit-for-bit the polygon the pick measures against.
/// <para>
/// <b>Threading:</b> render thread only, like the <see cref="DebugDraw"/> it
/// fills.
/// </para>
/// </remarks>
public static class RotateGizmoRenderer
{
    /// <summary>
    /// Pushes the whole gizmo into <paramref name="output"/>.
    /// </summary>
    /// <param name="output">The frame's debug line accumulator.</param>
    /// <param name="geometry">This frame's gizmo geometry.</param>
    /// <param name="highlighted">
    /// The ring to draw highlighted — the hovered one while idle, the active one
    /// during a drag, or <see cref="GizmoHandle.None"/> for neither.
    /// </param>
    public static void Draw(DebugDraw output, in GizmoGeometry geometry, GizmoHandle highlighted)
    {
        ArgumentNullException.ThrowIfNull(output);

        if (geometry.IsBehindCamera || geometry.AxisLength <= 0f)
            return;

        for (GizmoHandle handle = GizmoHandle.AxisX; handle <= GizmoHandle.AxisZ; handle++)
        {
            if (geometry.TryGetRing(handle, out Vector3 axis, out float radius))
                GizmoColors.DrawCircle(output, geometry.Pivot, axis, radius, GizmoColors.For(handle, highlighted));
        }

        // The view ring is built directly in the camera basis rather than from
        // its normal: BuildRingBasis would pick an arbitrary reference and the
        // ring's vertex phase would rotate as the camera turned, which is
        // invisible in a full circle but would make the drawn and picked
        // polygons disagree by half a chord.
        if (geometry.Offers(GizmoHandle.Screen))
        {
            GizmoColors.DrawCircle(
                output,
                geometry.Pivot,
                geometry.ViewRight,
                geometry.ViewUp,
                geometry.ScreenRingRadius,
                GizmoColors.For(GizmoHandle.Screen, highlighted));
        }
    }

    /// <summary>
    /// Draws the drag's protractor: a spoke to where the ring was grabbed, a
    /// spoke to where the cursor has taken it, and the arc between them — the
    /// feedback that turns "the object spun" into "you have turned it 45°".
    /// </summary>
    /// <param name="output">The frame's debug line accumulator.</param>
    /// <param name="geometry">This frame's gizmo geometry.</param>
    /// <param name="axis">The unit axis being rotated about.</param>
    /// <param name="reference">Unit vector from the pivot to the grab point, in the ring's plane.</param>
    /// <param name="radius">The ring's radius.</param>
    /// <param name="angle">The swept angle in radians, signed about <paramref name="axis"/>.</param>
    public static void DrawSweep(
        DebugDraw output, in GizmoGeometry geometry, Vector3 axis, Vector3 reference, float radius, float angle)
    {
        ArgumentNullException.ThrowIfNull(output);

        Vector3 pivot = geometry.Pivot;
        Vector3 perpendicular = Vector3.Cross(axis, reference);
        Vector3 color = GizmoColors.Highlight;

        output.Line(pivot, pivot + reference * radius, color);

        // One chord per whole segment of the ring's own tessellation, so the arc
        // reads as part of the ring rather than as a separate, coarser shape.
        int steps = Math.Max(1, (int)MathF.Ceiling(
            MathF.Abs(angle) / MathF.Tau * GizmoHitTesting.RingSegments));

        Vector3 previous = pivot + reference * radius;
        for (int i = 1; i <= steps; i++)
        {
            float step = angle * i / steps;
            Vector3 direction = reference * MathF.Cos(step) + perpendicular * MathF.Sin(step);
            Vector3 point = pivot + direction * radius;
            output.Line(previous, point, color);
            previous = point;
        }

        output.Line(pivot, previous, color);
    }
}
