using Microsoft.CodeAnalysis.CSharp;
using System.Globalization;
using System.Text;

namespace SpectraEngine.Entities.Generator;

/// <summary>
/// Writes the other half of an attributed entity class: the keyvalue binder, the
/// input dispatch, the output declarations, the schema and the registration.
/// </summary>
/// <remarks>
/// <para>
/// <b>Every emitted type name is <c>global::</c>-qualified and no using is
/// emitted.</b> The generated file lands in the author's namespace, where a type
/// of theirs called <c>Entity</c> or a namespace called <c>System</c> is
/// perfectly legal, and a generator that resolved names the way hand-written
/// code does would break on it with an error in a file the author cannot edit.
/// </para>
/// <para>
/// <b>The emitter reads a model and nothing else.</b> It never sees a symbol, so
/// there is no route by which a compilation could reach the cached output.
/// </para>
/// </remarks>
internal static class EntityEmitter
{
    private const string Ns = "global::SpectraEngine.Core.Entities";

    /// <summary>The file name the generated source is added under.</summary>
    public static string HintName(EntityModel model)
    {
        var name = new StringBuilder(model.FullTypeName.Length + 8);
        foreach (char c in model.FullTypeName)
            name.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');

        return name.Append(".g.cs").ToString();
    }

    /// <summary>The generated half of <paramref name="model"/>'s class.</summary>
    public static string Emit(EntityModel model)
    {
        var w = new SourceWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();

        if (model.Namespace.Length > 0)
            w.Open($"namespace {model.Namespace}");

        for (int i = 0; i < model.ContainingTypes.Count; i++)
            w.Open(model.ContainingTypes[i]);

        w.Open($"partial class {model.TypeName}");

        EmitClassName(w, model);
        EmitSchemaField(w);
        EmitParseKeyValue(w, model);
        EmitAcceptInput(w, model);
        EmitOutputs(w, model);
        EmitSchemaFactory(w, model);
        EmitRegistration(w, model);

        w.Close();

        for (int i = 0; i < model.ContainingTypes.Count; i++)
            w.Close();

        if (model.Namespace.Length > 0)
            w.Close();

        return w.ToString();
    }

    private static void EmitClassName(SourceWriter w, EntityModel model)
    {
        w.Line("/// <summary>The wire name a map file spells to place one of these.</summary>");
        w.Line($"public const string SpectraClassName = {Literal(model.ClassName)};");
        w.Line();
    }

    private static void EmitSchemaField(SourceWriter w)
    {
        w.Line("/// <summary>What an editor and the runtime know about this class.</summary>");
        w.Line($"public static readonly {Ns}.EntitySchema SpectraSchema = CreateSpectraSchema();");
        w.Line();
    }

    private static void EmitParseKeyValue(SourceWriter w, EntityModel model)
    {
        if (model.Keyvalues.Count == 0)
            return;

        w.Line("/// <inheritdoc/>");
        w.Open("public override bool ParseKeyValue(string key, string value)");
        w.Open("switch (key)");

        for (int i = 0; i < model.Keyvalues.Count; i++)
        {
            KeyvalueModel keyvalue = model.Keyvalues[i];
            KeyvalueBinding.TryGet(keyvalue.Type, out KeyvalueRow row);
            w.Line($"case {Literal(keyvalue.Name)}:");

            if (row.Reader is null)
            {
                // The wire form IS the value, so there is nothing to read and
                // nothing that can be refused.
                w.Indent();
                w.Line($"this.{keyvalue.MemberName} = value;");
                w.Line("return true;");
                w.Outdent();
                continue;
            }

            // Braces per case, so each one gets its own 'parsed'.
            w.Line("{");
            w.Indent();

            if (keyvalue.Type == KeyvalueBinding.NodeRefValue)
            {
                // The empty string is how "no reference" is written, and the
                // reader refuses it deliberately so an unset reference is never
                // confused with one pointing at a node that is gone.
                w.Open("if (value.Length == 0)");
                w.Line($"this.{keyvalue.MemberName} = global::System.Guid.Empty;");
                w.Line("return true;");
                w.Close();
                w.Line();
            }

            w.Open($"if (!{Ns}.KeyvalueWire.{row.Reader}(value, out {row.CSharpType} parsed))");
            // Recognised the key, could not read the value: the default stands
            // and the load continues.
            w.Line("RefuseKeyvalue(key, value);");
            w.Line("return true;");
            w.Close();
            w.Line();
            w.Line($"this.{keyvalue.MemberName} = parsed;");
            w.Line("return true;");
            w.Outdent();
            w.Line("}");
        }

        w.Line("default:");
        w.Indent();
        w.Line("return base.ParseKeyValue(key, value);");
        w.Outdent();
        w.Close();
        w.Close();
        w.Line();
    }

    private static void EmitAcceptInput(SourceWriter w, EntityModel model)
    {
        if (model.Inputs.Count == 0)
            return;

        w.Line("/// <inheritdoc/>");
        w.Open($"public override bool AcceptInput(string input, ref {Ns}.EntityInputContext context)");
        w.Open("switch (input)");

        for (int i = 0; i < model.Inputs.Count; i++)
        {
            InputModel input = model.Inputs[i];
            w.Line($"case {Literal(input.Name)}:");
            w.Indent();
            w.Line($"this.{input.MethodName}(ref context);");
            w.Line("return true;");
            w.Outdent();
        }

        w.Line("default:");
        w.Indent();
        w.Line("return base.AcceptInput(input, ref context);");
        w.Outdent();
        w.Close();
        w.Close();
        w.Line();
    }

    private static void EmitOutputs(SourceWriter w, EntityModel model)
    {
        for (int i = 0; i < model.Outputs.Count; i++)
        {
            string output = model.Outputs[i];
            w.Line($"/// <summary>Fires <c>{output}</c> along every wire a map authored on it.</summary>");
            w.Line($"private void Fire{output}(");
            w.Indent();
            w.Line($"{Ns}.Entity? activator = null,");
            w.Line("string? parameterOverride = null) =>");
            w.Line($"FireOutput({Literal(output)}, activator, parameterOverride);");
            w.Outdent();
            w.Line();
        }
    }

    private static void EmitSchemaFactory(SourceWriter w, EntityModel model)
    {
        w.Open($"private static {Ns}.EntitySchema CreateSpectraSchema()");

        EmitKeyvalueArray(w, model);
        w.Line();

        var inputNames = new string[model.Inputs.Count];
        for (int i = 0; i < inputNames.Length; i++)
            inputNames[i] = model.Inputs[i].Name;

        var outputNames = new string[model.Outputs.Count];
        for (int i = 0; i < outputNames.Length; i++)
            outputNames[i] = model.Outputs[i];

        EmitNameArray(w, "inputs", inputNames);
        EmitNameArray(w, "outputs", outputNames);
        w.Line();

        w.Line($"return new {Ns}.EntitySchema(");
        w.Indent();
        w.Line($"{Literal(model.ClassName)},");
        w.Line($"{Literal(model.Display)},");
        w.Line($"{Literal(model.Group)},");
        w.Line($"{Ns}.EntityPlacement.{model.Placement},");
        // Always EngineCSharp: nothing branches on Origin (it is an editor badge)
        // and the generator has no signal that tells a game's own assembly apart
        // from the engine's.
        w.Line($"{Ns}.EntityOrigin.EngineCSharp,");
        w.Line("keyvalues,");
        w.Line("inputs,");
        w.Line("outputs);");
        w.Outdent();

        w.Close();
        w.Line();
    }

    private static void EmitKeyvalueArray(SourceWriter w, EntityModel model)
    {
        if (model.Keyvalues.Count == 0)
        {
            w.Line($"var keyvalues = global::System.Array.Empty<{Ns}.KeyvalueDescriptor>();");
            return;
        }

        w.Line($"var keyvalues = new {Ns}.KeyvalueDescriptor[]");
        w.Line("{");
        w.Indent();

        for (int i = 0; i < model.Keyvalues.Count; i++)
        {
            KeyvalueModel keyvalue = model.Keyvalues[i];
            KeyvalueBinding.TryGet(keyvalue.Type, out KeyvalueRow row);

            w.Line($"new {Ns}.KeyvalueDescriptor(");
            w.Indent();
            w.Line($"{Literal(keyvalue.Name)},");
            w.Line($"{Literal(keyvalue.Display)},");
            w.Line($"{Literal(keyvalue.Tooltip)},");
            w.Line($"{Literal(keyvalue.Default)},");
            w.Line($"{Ns}.KeyvalueType.{row.Name},");
            w.Line($"(byte){keyvalue.Widget.ToString(CultureInfo.InvariantCulture)},");
            w.Line($"{Float(keyvalue.Min)},");
            w.Line($"{Float(keyvalue.Max)},");
            w.Line("0u,");
            w.Line($"{Ns}.KeyvalueDescriptor.NoChoices),");
            w.Outdent();
        }

        w.Outdent();
        w.Line("};");
    }

    private static void EmitNameArray(SourceWriter w, string variable, string[] names)
    {
        if (names.Length == 0)
        {
            w.Line($"var {variable} = global::System.Array.Empty<string>();");
            return;
        }

        var text = new StringBuilder();
        for (int i = 0; i < names.Length; i++)
        {
            if (i > 0)
                text.Append(", ");
            text.Append(Literal(names[i]));
        }

        w.Line($"var {variable} = new string[] {{ {text} }};");
    }

    private static void EmitRegistration(SourceWriter w, EntityModel model)
    {
        w.Line("/// <summary>Registers this class into the process-wide catalogue.</summary>");
        w.Line("/// <remarks>");
        w.Line("/// A module initializer rather than a call some host has to remember, because a");
        w.Line("/// class nobody registered is a class every map naming it loads as a placeholder,");
        w.Line("/// with one warning and no behaviour. It still needs the assembly to be LOADED,");
        w.Line("/// which is what an anchor a host calls is for.");
        w.Line("/// </remarks>");
        w.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        w.Open("internal static void SpectraRegister()");
        w.Line($"{Ns}.EntityCatalog.Register(SpectraSchema, static () => new {model.TypeName}());");
        w.Close();
    }

    private static string Literal(string text) => SymbolDisplay.FormatLiteral(text, quote: true);

    private static string Float(float value)
    {
        if (float.IsNaN(value))
            return "float.NaN";
        if (float.IsPositiveInfinity(value))
            return "float.PositiveInfinity";
        if (float.IsNegativeInfinity(value))
            return "float.NegativeInfinity";

        // Round-trip, invariant: a bound written with the current culture would
        // emit "1,5" on half the machines in the world and not compile there.
        return value.ToString("R", CultureInfo.InvariantCulture) + "f";
    }
}
