using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using SpectraEngine.Physics.Box3D.Native;

namespace SpectraEngine.Physics.Tests;

/// <summary>
/// The ABI guard: every managed struct that mirrors a Box3D one is checked,
/// field by field, against a manifest generated from the C compiler itself.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why this is not optional hygiene.</b> A P/Invoke struct whose layout
/// disagrees with the library's does not fail to compile and does not throw —
/// it silently reads and writes the wrong bytes. Box3D is alpha and its API is
/// already breaking (upstream has bumped <c>b3HullData</c> and
/// <c>b3CompoundData</c> versions recently), so "the pin moved and a struct grew
/// a field" is a thing that <em>will</em> happen. The only question is whether
/// it presents as a red build or as physics that is subtly wrong in a way nobody
/// can reproduce.
/// </para>
/// <para>
/// <b>Why it reads a committed file instead of running the probe.</b> The
/// manifest is generated by <c>native/abi-probe</c> against the same headers and
/// the same precision flag as <c>box3d.dll</c>, and committed. So this test
/// needs no C toolchain and no native library — it runs on any machine, in any
/// configuration, including a shader-only build. Regenerating the manifest is a
/// deliberate step when the submodule pin moves, and the diff lands in review
/// where a human can see that a struct changed shape.
/// </para>
/// <para>
/// <b>What it deliberately does not check.</b> Function signatures. A wrong
/// parameter list is not detectable from layouts alone, and pretending otherwise
/// would make this look more complete than it is.
/// </para>
/// </remarks>
public sealed class Box3DAbiTests
{
    private static readonly Lazy<AbiManifest> Manifest = new(LoadManifest);

    [Fact]
    public void The_manifest_describes_the_build_we_actually_ship()
    {
        AbiManifest m = Manifest.Value;

        m.Precision.ShouldBe("float", "BOX3D_DOUBLE_PRECISION is off by decision, and the flag is ABI-affecting");
        m.PointerSize.ShouldBe(IntPtr.Size, "the manifest was generated for a different word size than this test runs at");
        m.Structs.ShouldNotBeEmpty();
    }

    [Theory]
    [InlineData(typeof(B3Version), "b3Version")]
    [InlineData(typeof(B3Vec3), "b3Vec3")]
    [InlineData(typeof(B3Quat), "b3Quat")]
    [InlineData(typeof(B3Transform), "b3Transform")]
    [InlineData(typeof(B3Pos), "b3Pos")]
    [InlineData(typeof(B3WorldTransform), "b3WorldTransform")]
    [InlineData(typeof(B3WorldId), "b3WorldId")]
    [InlineData(typeof(B3BodyId), "b3BodyId")]
    [InlineData(typeof(B3ShapeId), "b3ShapeId")]
    [InlineData(typeof(B3Capacity), "b3Capacity")]
    [InlineData(typeof(B3WorldDef), "b3WorldDef")]
    public void A_managed_struct_matches_its_native_layout(Type managed, string nativeName)
    {
        AbiManifest m = Manifest.Value;
        m.Structs.ShouldContainKey(nativeName, $"the manifest has no entry for '{nativeName}'");
        NativeStruct native = m.Structs[nativeName];

        Marshal.SizeOf(managed).ShouldBe(
            native.Size,
            $"{managed.Name} is {Marshal.SizeOf(managed)} bytes but native {nativeName} is {native.Size}");

        System.Reflection.FieldInfo[] fields =
            managed.GetFields(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);

        fields.Length.ShouldBe(
            native.Fields.Count,
            $"{managed.Name} has {fields.Length} fields but native {nativeName} has {native.Fields.Count}");

        for (int i = 0; i < fields.Length; i++)
        {
            // Positional, not by name: the managed names are C#-cased and the
            // native ones are not, and it is the ORDER that decides the layout.
            NativeField expected = native.Fields[i];
            int actualOffset = (int)Marshal.OffsetOf(managed, fields[i].Name);

            actualOffset.ShouldBe(
                expected.Offset,
                $"{managed.Name}.{fields[i].Name} sits at offset {actualOffset}, " +
                $"but native {nativeName}.{expected.Name} sits at {expected.Offset}");

            Marshal.SizeOf(fields[i].FieldType).ShouldBe(
                expected.Size,
                $"{managed.Name}.{fields[i].Name} is {Marshal.SizeOf(fields[i].FieldType)} bytes, " +
                $"but native {nativeName}.{expected.Name} is {expected.Size}");
        }
    }

    [Fact]
    public void The_guard_would_actually_catch_a_wrong_layout()
    {
        // A guard nobody has seen fail is a guard nobody knows works. This
        // deliberately-wrong struct swaps a ushort pair for two ints — the exact
        // shape of mistake that produces a handle which is silently wrong on
        // every single call rather than throwing anywhere.
        AbiManifest m = Manifest.Value;
        NativeStruct native = m.Structs["b3WorldId"];

        Marshal.SizeOf<DeliberatelyWrongWorldId>().ShouldNotBe(native.Size);
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct DeliberatelyWrongWorldId
    {
        public int Index1;
        public int Generation;
    }

    // --- Manifest parsing ---------------------------------------------------

    private sealed record NativeField(string Name, int Offset, int Size);

    private sealed record NativeStruct(string Name, int Size, int Align, List<NativeField> Fields);

    private sealed record AbiManifest(
        string Version, string Precision, int PointerSize, Dictionary<string, NativeStruct> Structs);

    private static AbiManifest LoadManifest()
    {
        string path = FindManifest();
        string version = "", precision = "";
        int pointerSize = 0;
        var structs = new Dictionary<string, NativeStruct>(StringComparer.Ordinal);
        NativeStruct? current = null;

        foreach (string raw in File.ReadLines(path))
        {
            string line = raw.Trim();
            if (line.Length == 0 || line.StartsWith('#'))
                continue;

            string[] parts = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            switch (parts[0])
            {
                case "version":
                    version = parts[1];
                    break;
                case "precision":
                    precision = parts[1];
                    break;
                case "pointer":
                    pointerSize = ParseTagged(parts, "size=");
                    break;
                case "struct":
                    current = new NativeStruct(parts[1], ParseTagged(parts, "size="), ParseTagged(parts, "align="), []);
                    structs[current.Name] = current;
                    break;
                case "field":
                    current.ShouldNotBeNull($"manifest has a field line before any struct line: '{line}'");
                    current!.Fields.Add(new NativeField(parts[1], ParseTagged(parts, "offset="), ParseTagged(parts, "size=")));
                    break;
                default:
                    throw new InvalidDataException($"Unrecognised manifest line: '{line}'");
            }
        }

        return new AbiManifest(version, precision, pointerSize, structs);
    }

    private static int ParseTagged(string[] parts, string tag)
    {
        foreach (string part in parts)
        {
            if (part.StartsWith(tag, StringComparison.Ordinal))
                return int.Parse(part[tag.Length..], CultureInfo.InvariantCulture);
        }

        throw new InvalidDataException($"Manifest line is missing '{tag}': {string.Join(' ', parts)}");
    }

    // Walks up from the test binary to the repo root. A missing manifest is a
    // loud failure naming the command that regenerates it, not a skipped test:
    // an ABI guard that quietly opts out when it cannot find its data is worse
    // than no guard, because the build stays green.
    private static string FindManifest()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            string candidate = Path.Combine(dir.FullName, "native", "box3d-abi.manifest");
            if (File.Exists(candidate))
                return candidate;
            dir = dir.Parent;
        }

        throw new FileNotFoundException(
            "Could not find native/box3d-abi.manifest walking up from " +
            $"'{AppContext.BaseDirectory}'. It is generated by the ABI probe and committed — " +
            "regenerate it with: native/build-box3d.ps1 -Abi");
    }
}
