<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Spectra.Kitchen.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Spectra.Kitchen\Spectra.Kitchen.csproj" />
    <ProjectReference Include="..\..\Spectra.Kitchen.CLI\Spectra.Kitchen.CLI.csproj" />
  </ItemGroup>

</Project>
