<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>spectrashade-lsp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpectraShade.Compiler\SpectraShade.Compiler.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.LanguageServer" />
  </ItemGroup>

</Project>
