<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Graphics\BaseShaders\**\*.spectrashade" />
    <EmbeddedResource Include="Graphics\BaseShaders\**\*.spectrashade" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Silk.NET" />
    <PackageReference Include="Silk.NET.Assimp" />
    <PackageReference Include="Silk.NET.Direct3D11" />
    <PackageReference Include="Silk.NET.Direct3D12" />
    <PackageReference Include="Silk.NET.Direct3D.Compilers" />
    <PackageReference Include="Silk.NET.DXGI" />
    <PackageReference Include="Silk.NET.GLFW" />
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.Maths" />
    <PackageReference Include="Silk.NET.OpenAL" />
    <PackageReference Include="Silk.NET.OpenCL" />
    <PackageReference Include="Silk.NET.OpenGL" />
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="Silk.NET.Windowing.Common" />
    <PackageReference Include="Silk.NET.XInput" />
  </ItemGroup>

</Project>
