using System;
using System.Collections.Generic;
using System.Numerics;

namespace SpectraEngine.Core.Bsp;

/// <summary>
/// A compiled static world: the result of running CSG over a set of brushes.
/// Holds the carved visible surfaces and a BSP tree for spatial queries, and
/// can produce a render mesh — all from one <see cref="Build"/> call.
/// </summary>
public sealed class CsgWorld
{
    private CsgWorld(IReadOnlyList<Brush> brushes, IReadOnlyList<Polygon> surfaces, BspTree bsp)
    {
        Brushes = brushes;
        Surfaces = surfaces;
        Bsp = bsp;
    }

    /// <summary>The source brushes the world was built from.</summary>
    public IReadOnlyList<Brush> Brushes { get; }

    /// <summary>The visible exterior surfaces of the brush union, in world space.</summary>
    public IReadOnlyList<Polygon> Surfaces { get; }

    /// <summary>A solid-leaf BSP tree over the carved geometry.</summary>
    public BspTree Bsp { get; }

    /// <summary>Carves the brushes and builds the BSP tree from the result.</summary>
    public static CsgWorld Build(IReadOnlyList<Brush> brushes)
    {
        Polygon[] surfaces = Csg.Carve(brushes);
        // Snap before welding so T-vertices land on the same grid as the edges
        // they're inserted into — keeps every shared vertex bit-identical.
        surfaces = VertexSnapper.Snap(surfaces);
        surfaces = TJunctionWelder.Weld(surfaces);
        BspTree bsp = BspTree.BuildFromSurfaces(surfaces);
        return new CsgWorld(brushes, surfaces, bsp);
    }

    /// <summary>
    /// Builds a position+normal+uv render mesh (8 floats per vertex) from the
    /// carved surfaces, matching the engine's standard vertex layout. UVs are
    /// generated by world-space planar projection on the surface's dominant
    /// axis — adjacent coplanar surfaces tile continuously.
    /// </summary>
    public (float[] Vertices, uint[] Indices) BuildMesh()
    {
        const float UvScale = 1.0f;
        var vertices = new List<float>();
        var indices = new List<uint>();

        foreach (Polygon poly in Surfaces)
        {
            Vector3 normal = poly.Surface.Normal;
            uint baseIndex = (uint)(vertices.Count / 8);

            // Project onto the two axes orthogonal to the dominant normal axis.
            float ax = MathF.Abs(normal.X), ay = MathF.Abs(normal.Y), az = MathF.Abs(normal.Z);
            foreach (Vector3 v in poly.Vertices)
            {
                float u, w;
                if (ax >= ay && ax >= az) { u = v.Z; w = v.Y; }      // facing X
                else if (ay >= az) { u = v.X; w = v.Z; }              // facing Y
                else { u = v.X; w = v.Y; }                            // facing Z

                vertices.Add(v.X); vertices.Add(v.Y); vertices.Add(v.Z);
                vertices.Add(normal.X); vertices.Add(normal.Y); vertices.Add(normal.Z);
                vertices.Add(u * UvScale); vertices.Add(w * UvScale);
            }

            for (uint i = 1; i + 1 < poly.VertexCount; i++)
            {
                indices.Add(baseIndex);
                indices.Add(baseIndex + i);
                indices.Add(baseIndex + i + 1);
            }
        }

        return (vertices.ToArray(), indices.ToArray());
    }
}
