// Emits the ACTUAL memory layout of every Box3D struct the managed binding
// mirrors, as a diffable text manifest.
//
// WHY THIS EXISTS. A P/Invoke struct whose layout disagrees with the C library's
// does not fail to compile and does not throw — it silently reads and writes the
// wrong bytes. Box3D is alpha and its API is already breaking (upstream has
// bumped b3HullData and b3CompoundData versions recently), so "the pin moved and
// a struct grew a field" is a thing that WILL happen, and the only question is
// whether it presents as a red build or as physics that is subtly wrong in a way
// nobody can reproduce.
//
// The manifest this prints is committed. A test compares the managed layouts
// against it with no C toolchain involved, so every developer gets the check for
// free; regenerating it is a deliberate step when the pin moves, and the diff
// lands in review where a human can see that a struct changed shape.
//
// Build: native/build-box3d.ps1 -Abi   (see native/README.md)

#include <stdio.h>
#include <stddef.h>

#include "box3d/base.h"
#include "box3d/box3d.h"
#include "box3d/collision.h"
#include "box3d/constants.h"
#include "box3d/id.h"
#include "box3d/math_functions.h"
#include "box3d/types.h"

#if defined( _MSC_VER )
#define ALIGN_OF( T ) __alignof( T )
#else
#define ALIGN_OF( T ) _Alignof( T )
#endif

#define DUMP_STRUCT( T ) \
	printf( "struct %s size=%zu align=%zu\n", #T, sizeof( T ), (size_t)ALIGN_OF( T ) )

// sizeof on a null-pointer member expression is not a dereference — it is
// evaluated entirely at compile time, so this is well defined.
#define DUMP_FIELD( T, F ) \
	printf( "  field %s offset=%zu size=%zu\n", #F, offsetof( T, F ), sizeof( ( (T*)0 )->F ) )

int main( void )
{
	printf( "# Box3D ABI manifest — generated by native/abi-probe, do not hand-edit\n" );

	b3Version version = b3GetVersion();
	printf( "version %d.%d.%d\n", version.major, version.minor, version.revision );

#if defined( BOX3D_DOUBLE_PRECISION )
	printf( "precision double\n" );
#else
	printf( "precision float\n" );
#endif

	printf( "pointer size=%zu\n", sizeof( void* ) );

	// --- base -------------------------------------------------------------
	DUMP_STRUCT( b3Version );
	DUMP_FIELD( b3Version, major );
	DUMP_FIELD( b3Version, minor );
	DUMP_FIELD( b3Version, revision );

	// --- math -------------------------------------------------------------
	DUMP_STRUCT( b3Vec3 );
	DUMP_FIELD( b3Vec3, x );
	DUMP_FIELD( b3Vec3, y );
	DUMP_FIELD( b3Vec3, z );

	DUMP_STRUCT( b3Quat );
	DUMP_FIELD( b3Quat, v );
	DUMP_FIELD( b3Quat, s );

	DUMP_STRUCT( b3Transform );
	DUMP_FIELD( b3Transform, p );
	DUMP_FIELD( b3Transform, q );

	// b3Pos and b3WorldTransform are typedefs of the two above in the float
	// build and DISTINCT structs in the double build. Dumped separately and
	// deliberately: the day someone flips BOX3D_DOUBLE_PRECISION, these two
	// lines are the ones that move, and the binding keeps them as separate
	// managed types precisely so that day is a regeneration and not a rewrite.
	DUMP_STRUCT( b3Pos );
	DUMP_FIELD( b3Pos, x );
	DUMP_FIELD( b3Pos, y );
	DUMP_FIELD( b3Pos, z );

	DUMP_STRUCT( b3WorldTransform );
	DUMP_FIELD( b3WorldTransform, p );
	DUMP_FIELD( b3WorldTransform, q );

	// --- ids --------------------------------------------------------------
	// Passed BY VALUE on nearly every call, so their layout is on the hot path
	// of every mistake.
	DUMP_STRUCT( b3WorldId );
	DUMP_FIELD( b3WorldId, index1 );
	DUMP_FIELD( b3WorldId, generation );

	DUMP_STRUCT( b3BodyId );
	DUMP_FIELD( b3BodyId, index1 );
	DUMP_FIELD( b3BodyId, world0 );
	DUMP_FIELD( b3BodyId, generation );

	DUMP_STRUCT( b3ShapeId );
	DUMP_FIELD( b3ShapeId, index1 );
	DUMP_FIELD( b3ShapeId, world0 );
	DUMP_FIELD( b3ShapeId, generation );

	return 0;
}
