// Emits the ACTUAL memory layout of every Box3D struct the managed binding
// mirrors, as a diffable text manifest.
//
// WHY THIS EXISTS. A P/Invoke struct whose layout disagrees with the C library's
// does not fail to compile and does not throw — it silently reads and writes the
// wrong bytes. Box3D is alpha and its API is already breaking (upstream has
// bumped b3HullData and b3CompoundData versions recently), so "the pin moved and
// a struct grew a field" is a thing that WILL happen, and the only question is
// whether it presents as a red build or as physics that is subtly wrong in a way
// nobody can reproduce.
//
// The manifest this prints is committed. A test compares the managed layouts
// against it with no C toolchain involved, so every developer gets the check for
// free; regenerating it is a deliberate step when the pin moves, and the diff
// lands in review where a human can see that a struct changed shape.
//
// Build: native/build-box3d.ps1 -Abi   (see native/README.md)

#include <stdio.h>
#include <stddef.h>

#include "box3d/base.h"
#include "box3d/box3d.h"
#include "box3d/collision.h"
#include "box3d/constants.h"
#include "box3d/id.h"
#include "box3d/math_functions.h"
#include "box3d/types.h"

#if defined( _MSC_VER )
#define ALIGN_OF( T ) __alignof( T )
#else
#define ALIGN_OF( T ) _Alignof( T )
#endif

#define DUMP_STRUCT( T ) \
	printf( "struct %s size=%zu align=%zu\n", #T, sizeof( T ), (size_t)ALIGN_OF( T ) )

// sizeof on a null-pointer member expression is not a dereference — it is
// evaluated entirely at compile time, so this is well defined.
#define DUMP_FIELD( T, F ) \
	printf( "  field %s offset=%zu size=%zu\n", #F, offsetof( T, F ), sizeof( ( (T*)0 )->F ) )

int main( void )
{
	printf( "# Box3D ABI manifest — generated by native/abi-probe, do not hand-edit\n" );

	b3Version version = b3GetVersion();
	printf( "version %d.%d.%d\n", version.major, version.minor, version.revision );

#if defined( BOX3D_DOUBLE_PRECISION )
	printf( "precision double\n" );
#else
	printf( "precision float\n" );
#endif

	printf( "pointer size=%zu\n", sizeof( void* ) );

	// --- base -------------------------------------------------------------
	DUMP_STRUCT( b3Version );
	DUMP_FIELD( b3Version, major );
	DUMP_FIELD( b3Version, minor );
	DUMP_FIELD( b3Version, revision );

	// --- math -------------------------------------------------------------
	DUMP_STRUCT( b3Vec3 );
	DUMP_FIELD( b3Vec3, x );
	DUMP_FIELD( b3Vec3, y );
	DUMP_FIELD( b3Vec3, z );

	DUMP_STRUCT( b3Quat );
	DUMP_FIELD( b3Quat, v );
	DUMP_FIELD( b3Quat, s );

	DUMP_STRUCT( b3Transform );
	DUMP_FIELD( b3Transform, p );
	DUMP_FIELD( b3Transform, q );

	// b3Pos and b3WorldTransform are typedefs of the two above in the float
	// build and DISTINCT structs in the double build. Dumped separately and
	// deliberately: the day someone flips BOX3D_DOUBLE_PRECISION, these two
	// lines are the ones that move, and the binding keeps them as separate
	// managed types precisely so that day is a regeneration and not a rewrite.
	DUMP_STRUCT( b3Pos );
	DUMP_FIELD( b3Pos, x );
	DUMP_FIELD( b3Pos, y );
	DUMP_FIELD( b3Pos, z );

	DUMP_STRUCT( b3WorldTransform );
	DUMP_FIELD( b3WorldTransform, p );
	DUMP_FIELD( b3WorldTransform, q );

	// --- world creation ---------------------------------------------------
	// b3WorldDef is the one struct here with NO upstream _Static_assert on its
	// size, so measuring it is the only check that exists. It also mixes
	// floats, one-byte bools, a uint32, seven pointers and a nested struct —
	// the exact shape where a hand-derived layout goes wrong quietly.
	DUMP_STRUCT( b3Capacity );
	DUMP_FIELD( b3Capacity, staticShapeCount );
	DUMP_FIELD( b3Capacity, dynamicShapeCount );
	DUMP_FIELD( b3Capacity, staticBodyCount );
	DUMP_FIELD( b3Capacity, dynamicBodyCount );
	DUMP_FIELD( b3Capacity, contactCount );

	DUMP_STRUCT( b3WorldDef );
	DUMP_FIELD( b3WorldDef, gravity );
	DUMP_FIELD( b3WorldDef, restitutionThreshold );
	DUMP_FIELD( b3WorldDef, hitEventThreshold );
	DUMP_FIELD( b3WorldDef, contactHertz );
	DUMP_FIELD( b3WorldDef, contactDampingRatio );
	DUMP_FIELD( b3WorldDef, contactSpeed );
	DUMP_FIELD( b3WorldDef, maximumLinearSpeed );
	DUMP_FIELD( b3WorldDef, frictionCallback );
	DUMP_FIELD( b3WorldDef, restitutionCallback );
	DUMP_FIELD( b3WorldDef, enableSleep );
	DUMP_FIELD( b3WorldDef, enableContinuous );
	DUMP_FIELD( b3WorldDef, workerCount );
	DUMP_FIELD( b3WorldDef, enqueueTask );
	DUMP_FIELD( b3WorldDef, finishTask );
	DUMP_FIELD( b3WorldDef, userTaskContext );
	DUMP_FIELD( b3WorldDef, userData );
	DUMP_FIELD( b3WorldDef, createDebugShape );
	DUMP_FIELD( b3WorldDef, destroyDebugShape );
	DUMP_FIELD( b3WorldDef, userDebugShapeContext );
	DUMP_FIELD( b3WorldDef, capacity );
	DUMP_FIELD( b3WorldDef, internalValue );

	// --- bodies and shapes ------------------------------------------------
	// Upstream pins some of these with _Static_assert of its own
	// (sizeof(b3ShapeDef)==120, sizeof(b3BodyDef)==104 in the float build,
	// sizeof(b3SurfaceMaterial)==40). Measuring them here anyway is not
	// redundant: an upstream assert proves the C struct is what upstream
	// expects, and this proves the MANAGED mirror is what the C struct is.
	DUMP_STRUCT( b3MotionLocks );
	DUMP_FIELD( b3MotionLocks, linearX );
	DUMP_FIELD( b3MotionLocks, linearY );
	DUMP_FIELD( b3MotionLocks, linearZ );
	DUMP_FIELD( b3MotionLocks, angularX );
	DUMP_FIELD( b3MotionLocks, angularY );
	DUMP_FIELD( b3MotionLocks, angularZ );

	DUMP_STRUCT( b3BodyDef );
	DUMP_FIELD( b3BodyDef, type );
	DUMP_FIELD( b3BodyDef, position );
	DUMP_FIELD( b3BodyDef, rotation );
	DUMP_FIELD( b3BodyDef, linearVelocity );
	DUMP_FIELD( b3BodyDef, angularVelocity );
	DUMP_FIELD( b3BodyDef, linearDamping );
	DUMP_FIELD( b3BodyDef, angularDamping );
	DUMP_FIELD( b3BodyDef, gravityScale );
	DUMP_FIELD( b3BodyDef, sleepThreshold );
	DUMP_FIELD( b3BodyDef, name );
	DUMP_FIELD( b3BodyDef, userData );
	DUMP_FIELD( b3BodyDef, motionLocks );
	DUMP_FIELD( b3BodyDef, enableSleep );
	DUMP_FIELD( b3BodyDef, isAwake );
	DUMP_FIELD( b3BodyDef, isBullet );
	DUMP_FIELD( b3BodyDef, isEnabled );
	DUMP_FIELD( b3BodyDef, allowFastRotation );
	DUMP_FIELD( b3BodyDef, enableContactRecycling );
	DUMP_FIELD( b3BodyDef, internalValue );

	DUMP_STRUCT( b3Filter );
	DUMP_FIELD( b3Filter, categoryBits );
	DUMP_FIELD( b3Filter, maskBits );
	DUMP_FIELD( b3Filter, groupIndex );

	DUMP_STRUCT( b3SurfaceMaterial );
	DUMP_FIELD( b3SurfaceMaterial, friction );
	DUMP_FIELD( b3SurfaceMaterial, restitution );
	DUMP_FIELD( b3SurfaceMaterial, rollingResistance );
	DUMP_FIELD( b3SurfaceMaterial, tangentVelocity );
	DUMP_FIELD( b3SurfaceMaterial, userMaterialId );
	DUMP_FIELD( b3SurfaceMaterial, customColor );
	DUMP_FIELD( b3SurfaceMaterial, padding );

	DUMP_STRUCT( b3ShapeDef );
	DUMP_FIELD( b3ShapeDef, name );
	DUMP_FIELD( b3ShapeDef, userData );
	DUMP_FIELD( b3ShapeDef, materials );
	DUMP_FIELD( b3ShapeDef, materialCount );
	DUMP_FIELD( b3ShapeDef, baseMaterial );
	DUMP_FIELD( b3ShapeDef, density );
	DUMP_FIELD( b3ShapeDef, explosionScale );
	DUMP_FIELD( b3ShapeDef, filter );
	DUMP_FIELD( b3ShapeDef, enableCustomFiltering );
	DUMP_FIELD( b3ShapeDef, isSensor );
	DUMP_FIELD( b3ShapeDef, enableSensorEvents );
	DUMP_FIELD( b3ShapeDef, enableContactEvents );
	DUMP_FIELD( b3ShapeDef, enableHitEvents );
	DUMP_FIELD( b3ShapeDef, enablePreSolveEvents );
	DUMP_FIELD( b3ShapeDef, invokeContactCreation );
	DUMP_FIELD( b3ShapeDef, updateBodyMass );
	DUMP_FIELD( b3ShapeDef, enableSpeculativeContact );
	DUMP_FIELD( b3ShapeDef, internalValue );

	DUMP_STRUCT( b3AABB );
	DUMP_FIELD( b3AABB, lowerBound );
	DUMP_FIELD( b3AABB, upperBound );

	// The hull limits, emitted so the managed pre-check cannot drift from the
	// values the library actually enforces. The EDGE limit is the one that
	// really binds: for a convex polyhedron Euler gives E = V + F - 2, so
	// V + F <= maxEdges + 2 — far tighter than the vertex and face caps taken
	// separately, and not documented anywhere.
	printf( "limit maxHullVertices value=%d\n", B3_MAX_HULL_VERTICES );
	printf( "limit maxHullFaces value=%d\n", B3_MAX_HULL_FACES );
	printf( "limit maxHullEdges value=%d\n", B3_MAX_HULL_EDGES );

	// --- ids --------------------------------------------------------------
	// Passed BY VALUE on nearly every call, so their layout is on the hot path
	// of every mistake.
	DUMP_STRUCT( b3WorldId );
	DUMP_FIELD( b3WorldId, index1 );
	DUMP_FIELD( b3WorldId, generation );

	DUMP_STRUCT( b3BodyId );
	DUMP_FIELD( b3BodyId, index1 );
	DUMP_FIELD( b3BodyId, world0 );
	DUMP_FIELD( b3BodyId, generation );

	DUMP_STRUCT( b3ShapeId );
	DUMP_FIELD( b3ShapeId, index1 );
	DUMP_FIELD( b3ShapeId, world0 );
	DUMP_FIELD( b3ShapeId, generation );

	return 0;
}
